sudo: required
services:
  - docker
  
before_install:
  - docker build -t rahulpaulhub/docker_react -f Dockerfile.dev .

script:
  - docker run rahulpaulhub/docker_react npm run test -- --coverage
  
